development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_depot
  pool: 5
  username: root
  password: tt1234
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_depot
  pool: 5
  username: root
  password: tt1234
  socket: /var/run/mysqld/mysqld.sock
